import { test } from 'node:test';
import assert from 'node:assert/strict';
import { regions,homes,defaults,search,normalizeConditions,comparison } from '../src/data.js';
import { runAgent } from '../src/agent.js';
test('all 17 regions have distinct, usable synthetic candidates',()=>{
 assert.equal(regions.length,17);assert.equal(homes.length,68);assert.equal(new Set(homes.map(h=>h.id)).size,68);
 for(const r of regions){const c={...defaults,region:r.name};const found=search(c);assert.ok(found.length>0);assert.ok(found.every(h=>h.region===r.name&&h.total<=c.budget&&h.deposit<=c.deposit&&h.transit<=c.commute&&h.size>=c.minSize));}
});
test('hard constraints exclude candidates and zero results are not silently relaxed',()=>{assert.equal(search({...defaults,budget:1}).length,0);assert.equal(search({...defaults,deposit:0}).length,0);assert.equal(search({...defaults,commute:1}).length,0);assert.equal(search({...defaults,minSize:90}).length,0);});
test('score is deterministic, bounded, and comparison uses the same calculation',()=>{const found=search(defaults);assert.deepEqual(search(defaults),found);for(const h of found){assert.equal(h.fit+h.hii,100);assert.ok(h.hii>=0&&h.hii<=100);assert.deepEqual(comparison([h.id],defaults)[0],h);assert.ok(Math.abs(h.components.reduce((sum,c)=>sum+c.weight,0)-1)<.00001);}});
test('untrusted tool conditions are bounded and unknown regions ignored',()=>{const c=normalizeConditions({region:'unknown',budget:-2,commute:'invalid',deposit:Infinity,priority:'invalid'});assert.equal(c.region,defaults.region);assert.equal(c.budget,1);assert.equal(c.commute,defaults.commute);assert.equal(c.deposit,defaults.deposit);});
test('agent executes model tool calls, returns results, then gets final answer',async()=>{const original=global.fetch;let n=0;let called=false;global.fetch=async(url,opts)=>{n++;const body=JSON.parse(opts.body);if(n===1)return {ok:true,json:async()=>({candidates:[{content:{role:'model',parts:[{functionCall:{name:'search_candidates',args:{budget:50}},thoughtSignature:'test-signature'}]}}]})};assert.equal(body.contents[2].parts[0].functionResponse.response.result.count,2);assert.equal(body.contents[1].parts[0].thoughtSignature,'test-signature');return{ok:true,json:async()=>({candidates:[{content:{role:'model',parts:[{text:'두 후보를 찾았습니다.'}]}}]})};};try{const result=await runAgent({key:'test-only',model:'test-model',text:'50만 원',history:[],conditions:defaults,execute:(name,args)=>{called=true;assert.equal(name,'search_candidates');assert.equal(args.budget,50);return{count:2};},onStep:()=>{},signal:new AbortController().signal});assert.ok(called);assert.equal(result.text,'두 후보를 찾았습니다.');assert.equal(n,2);}finally{global.fetch=original;}});
